version: '3'

services:
  authentication_database_server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - authentication_database_volume:/var/lib/mysql
    networks:
      - authentication_network
  authentication_database_migration:
    image: authentication_database_migration:latest
    networks:
      - authentication_network
  authentication_service:
    image: authentication:latest
    ports:
      - '5000:5000'
    networks:
      - authentication_network
  redis:
    image: redis:latest
    volumes:
      - redis_volume:/data
    networks:
      - warehouse_network
      - daemon_network
  shop_database_server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - shop_database_volume:/var/lib/mysql
    networks:
      - daemon_network
      - customer_network
      - admin_network
      - shop_database_network
  shop_database_migration:
    image: shop_database_migration:latest
    networks:
      - shop_database_network
  warehouse_service:
    image: warehouse:latest
    ports:
      - '5001:5000'
    networks:
      - warehouse_network
  daemon:
    image: daemon:latest
    networks:
      - daemon_network
  customer_service:
    image: customer:latest
    ports:
      - '5002:5000'
    networks:
      - customer_network
  admin_service:
    image: admin:latest
    ports:
      - '5003:5000'
    networks:
      - admin_network

volumes:
  authentication_database_volume:
  redis_volume:
  shop_database_volume:

networks:
  authentication_network:
  warehouse_network:
  daemon_network:
  customer_network:
  admin_network:
  shop_database_network:
